### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#12]
[bdclean folder](https://drive.google.com/drive/folders/0B2OvnmJ4AtmtNmVtbERzRG1PVlU?usp=sharing) (Google Drive)

Here are some great resources when developing an R package:
* [Mastering Software Development in R](https://bookdown.org/rdpeng/RProgDA/)
* [CRAN- Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html)
* [How to develop good R packages (Maëlle Salmon)](http://www.masalmon.eu/2017/12/11/goodrpackages/)

Shiny tips & tricks:
* [advanced-shiny](https://github.com/rstats-gsoc/gsoc2018/wiki/bdclean%3A-User-friendly-biodiversity-data-cleaning-pipeline)

**Comment by tom-gu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [zxcvvsd](https://trello.com/c/593uaBku/1-zxcvvsd)

**Comment by thiloshon** [comment]
Migrated to Trello
