### ISSUE TITLE
Require peer review to merge pulls

### ISSUE THREAD

**Issue by thiloshon** [vijaybarve/bdclean#18]
Shall we make it compulsory for a pull request to be reviewed by at least one other, to be able to merge it with master?

Right now I am able to send a PR and then merge it myself which is not good practice. Review will ensure the PR is in the accepted quality and free from any future conflicts.

https://help.github.com/articles/enabling-required-reviews-for-pull-requests/ this explains how to setup the feature.

**Comment by vijaybarve** [comment]
I think this is good practice to let someone else merge pull request after testing it once.

**Comment by tom-gu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bdtools](https://trello.com/c/fwUNn3Fx/6-bdtools)

**Comment by thiloshon** [comment]
Added compulsory code review and Issues template.
