### ISSUE TITLE
DwC grouping mechanism + tabular data R viewer 

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#25]
Combining our DwC fields grouping mechanism and a really good tabular data R viewer (if exists???) can be really helpful when reviewing DwC data in R. If we can't find a decent viewer, I wonder if maybe we can implement the fields grouping mechanism in OpenRefine...

**Comment by thiloshon** [comment]
A summarized dataframe viewing function is already implemented in bdclean. We can extend that and make a complete 'Data View' feature set with grouping. OpenRefine is good option as well.

**Comment by thiloshon** [comment]
Added to 0.2 milestone

**Comment by tom-gu** [comment]
Moved to bdvis dashboards project
