### ISSUE TITLE
Visualizing bdclean architecture

### ISSUE THREAD

**Issue by thiloshon** [vijaybarve/bdclean#29]
I created few slides to better understand how bdclean will be structured and how it will interact with other packages in the bdverse ecosystem. 

Access the slide [here ](https://docs.google.com/presentation/d/1NihlCSjFIIpdYlj-iIia1UJXBIzaTP61iF-0cQrl6e0/edit?usp=sharing) and any suggestion is welcomed.

**Comment by tom-gu** [comment]
Fantastic!
In slide 5 I would use only these tabs:
**Load data** | **Summary report** | **Questionnaire** | **Make decisions** (optional name) | **Cleaning report** | **Save data**

Now, try to visualize each tab as much as possible - go into as many details as possible. And then you are welcome to revise your functionality design. Try to identify missing elements and \ or any doubts you can think off.

Again, great job! :bowtie:

**Comment by thiloshon** [comment]
Thank you for the response @tom-gu  :)

I have added 4 new slides with breakdown for each tab. Please let me know what you think.

**Comment by thiloshon** [comment]
Followed this and developed the system. Closing as not applicable anymore...
