### ISSUE TITLE
Perform Header Cleaning crashes the bdclean app

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#48]
![image](https://user-images.githubusercontent.com/16609623/55279261-99c27a00-5327-11e9-9227-79cf31aa976e.png)

**Console Error:**
![image](https://user-images.githubusercontent.com/16609623/55279268-c4143780-5327-11e9-9fb3-4e04debf7a11.png)

For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=10:10

**Comment by PoGibas** [comment]
Current development `bdDwC` version on GitHub has different function names:

- `bdDwC::darwinize_names`  instead of `bdDwC::darwinizeNames`
- `bdDwC::rename_user_data`  instead of `bdDwC::renameUserData`

These names might change in future versions.

**Comment by thiloshon** [comment]
Fixed
