### ISSUE TITLE
The questionnaire is not really resetting itself

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#50]
After answering the questionnaire >> Flagging >> returning to the questionnaire and changing the answers >> some input from the first of the questionnaire session still exist.
**A simple example:**

Fresh bdclean session>> answering the questionnaire: 
![image](https://user-images.githubusercontent.com/16609623/55279571-f70bfa80-532a-11e9-8920-0f65e3315c6d.png)

Performing flagging:
![image](https://user-images.githubusercontent.com/16609623/55279583-1d319a80-532b-11e9-81ef-2f96e1ff6955.png)

Results:
![image](https://user-images.githubusercontent.com/16609623/55279589-34708800-532b-11e9-947e-36b9d87e2c4a.png)

Now, changing the questionnaire to:
![image](https://user-images.githubusercontent.com/16609623/55279598-523ded00-532b-11e9-8019-1bceaf079a16.png)

Results aren't changing as they should:
![image](https://user-images.githubusercontent.com/16609623/55279626-9630f200-532b-11e9-842e-2f7b26def315.png)

For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=11:11

**Comment by thiloshon** [comment]
This is caused because BDQuestion reference class wasnt resetting when questionnaire is changed. The old values still remained. This is fixed now

**Comment by thiloshon** [comment]
#56
