### ISSUE TITLE
Running any check from bdchecks crashes bdclean

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#51]
Running any check from bdchecks crashes bdclean, console error massage:
![image](https://user-images.githubusercontent.com/16609623/55285282-3bca7c80-5391-11e9-82e1-37766cf16d54.png)

For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=12:12

**Comment by PoGibas** [comment]
Current development bdchecks version on GitHub has different function names:

- `bdchecks::dc_perform`  instead of `bdchecks::performDataCheck`

These names might change in future versions.

**Comment by thiloshon** [comment]
Fixed
