### ISSUE TITLE
in version 0.1.13 questionnaire is not available

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#52]
In the newest version (thiloshon/bdclean; 0.1.13) : questionnaire is not available:
![image](https://user-images.githubusercontent.com/16609623/55285747-1db54a00-539a-11e9-8744-d592b1001c61.png)

Console Error:
![image](https://user-images.githubusercontent.com/16609623/55285752-37ef2800-539a-11e9-914d-2b29264bb48e.png)

For more details see QA working file:
https://docs.google.com/spreadsheets/d/1VFhHy6uo7qVBiHhcuLqUJ3RXKpaG-4C3RD0jqvB0xtU/edit#gid=21537633&range=13:13

**Comment by thiloshon** [comment]
Fixed
