### ISSUE TITLE
Data Checks

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#6]
[Data checks characterization (GoogleDocs) ](https://docs.google.com/document/d/1atmn0fp94_nb-exycghaxPtDnfmy_I5i5nUAISgsPoQ/edit)

[Data checks DB (GoogleSheets)](https://docs.google.com/spreadsheets/d/1TsxQbzoZ4bjz30FINsztcQO9hIKqBK1KtszmtWMtocU/edit#gid=1444049182)

**Comment by AshwinAgrawal16** [comment]
Currently there are only few basic questions in the package, so we can start converting the data checks developed by me and @thiloshon into questions according to the above template. This way we can also check what some other functionalities need to be developed if we face some complex questions and in a way this will check the robustness of the package structure. @vijaybarve @tom-gu

**Comment by vijaybarve** [comment]
@AshwinAgrawal16 Sounds good. Can you and @thiloshon please start listing questions for data checks, that you have developed and think are ready to be integrated in the package. Once you have the draft questions, me and @tom-gu can help refine them. Also start listing issues for remaining data checks that you think needs bit more fine tuning.

**Comment by AshwinAgrawal16** [comment]
Yes I will start preparing the draft of the questions for the data checks which I have developed.

**Comment by thiloshon** [comment]
Ack Vijay! I will do it.

**Comment by thiloshon** [comment]
Implemented in bdclean
