### ISSUE TITLE
bdclean crushes (bdclean-bdchecks bug)

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#65]
Happens almost every time :sob:
![image](https://user-images.githubusercontent.com/16609623/70130903-18777000-168a-11ea-94e9-b0b6bac2adba.png)
****

**Comment by thiloshon** [comment]
This is fixed in latest version and not reprodicible in binder. @tom-gu can you please verify and close?

**Comment by tom-gu** [comment]
~~@thiloshon it seems to work perfectly **only** for gbif data retrieved via the API :dizzy_face:
In binder- try non-gbif data (e.g. Puma concolor from iDigbio). 
Also, you can try any RDS file from the zip file attached.~~









[spooc_data_1r.zip](https://github.com/bd-R/bdclean/files/4009888/spooc_data_1r.zip)

**Comment by tom-gu** [comment]
@thiloshon oops! the comment above is related to issue https://github.com/bd-r/bddwc.app/issues/11, copying it there.
:sweat_smile::sweat_smile::sweat_smile:

**Comment by thiloshon** [comment]
@PoGibas 
This issue is originating from bdchecks. 

```
...
...
...
Warning in bdchecks::perform_dc(data = flagged_data, wanted_dc = c(check_name)) :
  Column specificEpithet does not exist in a given dataset; skipping data check validation_taxon_empty for it.
Warning in bdchecks::perform_dc(data = flagged_data, wanted_dc = c(check_name)) :
  Column infraspecificEpithet does not exist in a given dataset; skipping data check validation_taxon_empty for it.
Warning in bdchecks::perform_dc(data = flagged_data, wanted_dc = c(check_name)) :
  Column vernacularName does not exist in a given dataset; skipping data check validation_taxon_empty for it.
Warning: Error in rowSums: 'x' must be an array of at least two dimensions
  81: stop
  80: rowSums
  79: bdchecks::perform_dc
  78: question$flag_data
  77: data_store()[[checks]]$flag_data
  73: observeEventHandler [modules/flagging-module.R#61]
   2: shiny::runApp
   1: bdclean_app
```

When the dataset doesn't contain any fields that are matched with the fields required by checks, the _rowSums_ in perform_dc function of bdchecks throws error as its empty.
<img width="669" alt="Screen Shot 2019-12-31 at 2 40 04 PM" src="https://user-images.githubusercontent.com/17028697/71616285-76409e80-2bdb-11ea-822e-77c21d21c92a.png">

But what confuses me is, in local setups this works without issue, but in binder this rowSums error is thrown. Any idea why?

**Comment by tom-gu** [comment]
@thiloshon I updated bdverse DESCRIPTION to make the binder env up to date
https://github.com/bd-R/bdverse/commit/e507601ab02b12d62c9dffa894a435bb74ccef92

**Comment by thiloshon** [comment]
@tom-gu Ack!

**Comment by thiloshon** [comment]
After binder update, not reproducible.

**Comment by tom-gu** [comment]
Unfurtianly, in some cases, they can also have data frames within a list within a date frame :anguished: (e.g inaturalist).  Flattening the data won't work for all cases. I have a slick idea for a safe way of downloading the data. It will be easier to discuss it in our next meeting @thiloshon
