### ISSUE TITLE
App is crushing

### ISSUE THREAD

**Issue by tom-gu** [vijaybarve/bdclean#86]
## Data
![image](https://user-images.githubusercontent.com/16609623/138372997-9f795cc6-847e-4ddc-9c6f-93bc18930a11.png)

## Questionnaire
![image](https://user-images.githubusercontent.com/16609623/138373090-dc4e6ffe-f453-429e-88e3-1243d23913ff.png)

## Flag Data
![image](https://user-images.githubusercontent.com/16609623/138373125-f6d2ce41-e5b4-4ff2-bebc-686cfba325d4.png)

## Console
![image](https://user-images.githubusercontent.com/16609623/138373179-d5b84f3c-6711-4214-b77a-a87aee36e303.png)

**Comment by rahulchauhan049** [comment]
@tom-gu I am unable to reproduce the bug. Can you please add more instructions to reproduce the bug?

**Comment by tom-gu** [comment]
@rahulchauhan049  make sure to install bdverse@dev it has all the dev branches

![image.png](https://images.zenhubusercontent.com/59e62044a468affe6df6fea1/b0c389bc-0ea9-4dd0-9aa0-ae44c47d13c6)

**Comment by tom-gu** [comment]
RStudio Project with bdverse@dev installed (for reproducibility):
https://rstudio.cloud/project/2700632
@rahulchauhan049 @thiloshon

**Comment by tom-gu** [comment]
Firefox seems to work the best with RStudio Cloud

**Comment by rahulchauhan049** [comment]
I've noticed that the issue is only in the dev branch, the main branch working fine. Also, the dev branch is 27 commits ahead, 38 commits behind the main.
Should we merge main in dev?

**Comment by thiloshon** [comment]
https://github.com/bd-R/bdclean/pull/87

This should ideally fix the issue. @tom-gu please review and merge.

**Comment by tom-gu** [comment]
Working :-)
Thank you @thiloshon !
Thank you @rahulchauhan049 !
I'll merge the PR
